import fs from'node:fs';import * as T from'three';import{loadGLB}from'../load-glb-node.mjs';import{ActorAnimation}from'../../src/game/animation-controller.js';import{SoleClearance}from'../../src/game/sole-clearance.js';import{FootPlant}from'../../src/game/foot-plant.js';import metadata from'../../docs/player-essential-manifest.json'with{type:'json'};
const path=process.argv[2]||'assets/player-essential-motion/player-gait-support-final.glb',g=await loadGLB(path),anim=new ActorAnimation(g.scene,g.animations,metadata),soles=new SoleClearance(g.scene),plant=new FootPlant(g.scene,soles),names=g.animations.filter(c=>/^(run|walk)-/.test(c.name)).map(c=>c.name),knees=['Left','Right'].map(s=>g.scene.getObjectByName('mixamorig'+s+'Leg'));
let minimum=0,maxCorrection=0,maxKneeStep=0,worstSole=null,worstStep=null;const rows=[];
for(const from of names)for(const to of names){if(from===to)continue;let pairMin=0,pairStep=0,pairCorrection=0;
 for(const phase of [0,.125,.25,.375]){anim.reset();anim.update(0,from,{speed:metadata.clips[from].sourceSpeed});anim.layers.get(from).time=anim.layers.get(from).action.getClip().duration*phase;anim.update(0,from,{speed:metadata.clips[from].sourceSpeed});g.scene.updateMatrixWorld(true);plant.correct();let previous=knees.map(k=>k.quaternion.clone());
 for(let frame=0;frame<20;frame++){anim.update(1/60,to,{speed:metadata.clips[to].sourceSpeed});g.scene.updateMatrixWorld(true);plant.correct();const lo=soles.minimumHeight(),q=knees.map(k=>k.quaternion.clone()),step=Math.max(...q.map((v,i)=>v.angleTo(previous[i])*180/Math.PI));previous=q;pairMin=Math.min(pairMin,lo);pairStep=Math.max(pairStep,step);pairCorrection=Math.max(pairCorrection,plant.maxCorrection);
 if(lo<minimum){minimum=lo;worstSole={from,to,phase,frame,lo};}if(step>maxKneeStep){maxKneeStep=step;worstStep={from,to,phase,frame,step};}maxCorrection=Math.max(maxCorrection,plant.maxCorrection);
 }}rows.push({from,to,minimum:pairMin,maxKneeStep:pairStep,maxCorrection:pairCorrection});}
const summary={asset:path,pairs:rows.length,phasesPerPair:4,minimum,maxCorrection,maxKneeStep,worstSole,worstStep};fs.writeFileSync(process.argv[3]||'docs/player-gait-transition-matrix.json',JSON.stringify({summary,rows},null,2));console.log(JSON.stringify(summary,null,2));
