import test from 'node:test';import assert from'node:assert/strict';import{Fight,PLAYER_DAMAGE_TAKEN}from'../src/game/encounter.js';import{sweptWeaponContact,segmentDistance}from'../src/game/weapon-motion.js';
const advance=(f,seconds,g={distance:10,playerHit:false,bossHit:false,playerFacing:true})=>{for(let i=0;i<Math.ceil(seconds*120);i++)f.step(1/120,g)};
function active(){const f=new Fight();f.start();return f;}
test('swept blade catches a capsule crossed between endpoints and misses distant bodies',()=>{const prev=[[-1,1,-1],[-1,1,1]],cur=[[1,1,-1],[1,1,1]],body=[[0,.4,0],[0,1.6,0]];assert.equal(sweptWeaponContact(prev,cur,body,.2),true);assert.equal(sweptWeaponContact(prev,cur,[[4,.4,0],[4,1.6,0]],.2),false);assert.equal(segmentDistance([0,0,0],[0,0,0],[1,0,0],[1,0,0]),1);});
test('attack hit is geometry gated, only inside active window, and once per strike',()=>{const f=active();f.request('light');advance(f,.27,{distance:1,playerHit:true});assert.equal(f.boss.health,1800);advance(f,.3,{distance:1,playerHit:true});assert.equal(f.boss.health,1745);advance(f,.6,{distance:1,playerHit:true});assert.equal(f.boss.health,1745);f.request('heavy');advance(f,2,{distance:1,playerHit:false});assert.equal(f.boss.health,1745);});
test('blocking spends stamina, reduces damage, and insufficient stamina breaks guard',()=>{const f=active();f.playerDamageTaken=1;/* rule values at the unscaled damage */f.player.blocking=true;f.boss.action={name:'sweep',elapsed:1.099,hits:[]};f.step(1/120,{distance:2,bossHit:true,playerFacing:true});assert.equal(f.player.health,96);assert.equal(f.player.stamina,68);f.player.stamina=10;f.boss.action={name:'sweep',elapsed:1.099,hits:[]};f.step(1/120,{distance:2,bossHit:true,playerFacing:true});assert.equal(f.player.health,67);assert.ok(f.drain().some(e=>e.type==='guard-break'));});
test('dodge immunity is timed and healing can be interrupted',()=>{const f=active();f.request('dodge');advance(f,.1);f.boss.action={name:'sweep',elapsed:1.099,hits:[]};f.step(1/120,{distance:2,bossHit:true});assert.equal(f.player.health,100);assert.equal(f.stats.evades,1);advance(f,1);f.player.health=40;f.request('heal');advance(f,.3);f.boss.action={name:'slam',elapsed:1.499,hits:[]};f.step(1/120,{distance:2,bossHit:true});assert.equal(f.player.flasks,2);assert.equal(f.status,'defeat');});
test('two-swing combo has exactly two independently resolved strikes',()=>{const f=active();f.playerDamageTaken=1;/* rule values at the unscaled damage */f.boss.phase=2;f.boss.action={name:'combo',elapsed:1.24,hits:[]};advance(f,1.2,{distance:2,bossHit:true});assert.equal(f.player.health,50);assert.equal(f.stats.hits,2);});
test('phase changes once; win freezes input; ten retries fully reset state',()=>{const f=active();f.boss.health=890;advance(f,.1);assert.equal(f.boss.phase,2);assert.equal(f.drain().filter(e=>e.type==='phase-change').length,1);f.boss.health=20;f.request('light');advance(f,.6,{distance:2,playerHit:true});assert.equal(f.status,'victory');assert.equal(f.request('heal'),false);for(let i=0;i<10;i++){f.reset();assert.deepEqual(f,new Fight());f.start();f.player.health=0;advance(f,.01);assert.equal(f.status,'defeat');}});
test('fixed-step integration is independent of the presentation frame rate',()=>{function run(fps){const f=active();let rem=0;for(let i=0;i<fps*12;i++){rem+=1/fps;while(rem+1e-10>=1/120){rem-=1/120;f.step(1/120,{distance:2,bossHit:true,playerFacing:true});}}return f;}assert.deepEqual(run(30),run(60));assert.deepEqual(run(60),run(120));});

test('the player takes 1.25x damage by default (health effectively 20 % lower)',()=>{const f=active();assert.equal(f.playerDamageTaken,PLAYER_DAMAGE_TAKEN);assert.equal(PLAYER_DAMAGE_TAKEN,1.25);f.boss.phase=2;f.boss.action={name:'combo',elapsed:1.24,hits:[]};advance(f,1.2,{distance:2,bossHit:true});assert.equal(f.player.health,38);});