"""Queue the explicitly authorized five player source videos once; keep all job IDs.

Run one named clip per invocation. Existing job logs prevent accidental duplicate
billing. Video review and explicit --video extraction are separate later steps.
"""
import json, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOC = ROOT / 'docs/player-combat-revision'
REF = ROOT / 'assets/use-the-supplied-screenshot-as-a-visual-cmu11v2l.png'
BASE = '''A readable realistic full-body combat motion reference for animation extraction. Image 1 defines the approved Thorn Exile armored warrior, sword in anatomical RIGHT hand, separate shield strapped to anatomical LEFT forearm. Preserve these designs and human proportions. Accurate natural closed right-hand sword grip: fingers encircle the handle, thumb opposes fingers, crossguard above index finger, blade extends beyond the thumb side of the fist; never grip the blade. Keep the left shield arm engaged but below the face. Shorten only loose trailing cloth in this motion study so knees and ankles are visible.

One character only, no enemies, no visual effects. Plain neutral gray studio and flat matte floor with clear contact shadows, even bright lighting to read joints and armor. Fixed wide three-quarter front SIDE camera at hip height, no pan, no zoom, no cuts, no slow motion. Whole body and sword remain visible with ample margins; warrior occupies only 55 percent of image height. Natural real-time biomechanical motion with readable anticipation, body weight, momentum and recovery. Boots visibly support the body's weight; pelvis, spine, shoulders, arms and legs work together. Avoid straight locked knees, leaning backward, robotic arm-only movement, sliding feet and camera motion. Start and finish in the same balanced staggered guard: left boot slightly forward, feet shoulder-width, flexed knees, hips over midfoot, chest slightly forward, sword ready in right hand and shield ready on left.

'''
MOTIONS = {
 'guard': '''For the entire five seconds, hold a poised sword-and-shield combat guard with subtle living motion. Weight is about evenly shared with slight forward intent. Sword hand beside the right lower ribs, bent right elbow away from armor, blade inclined forward and upward outside the torso, shield held in front of the left ribs. Both boots stay planted and knees softly flexed; controlled breathing expands chest and subtly shifts shoulders and pelvis. One slow restrained weight transfer through the whole body then return. Stay threatening and alert. No attack, no steps, no pose change, no weapon flourishes. Not a toy soldier, not a deep squat.''',
 'light': '''Perform exactly ONE purposeful one-handed RIGHT-TO-LEFT horizontal sword cut and recover. First 0.8 seconds balanced guard. Draw the right sword hand back outside the right hip and right shoulder while loading the rear/right leg and winding pelvis and chest clockwise from above. Then push through the rear boot and take one short forward left step as pelvis and shoulders unwind. Sweep the sword from the warrior's anatomical RIGHT side across the front to anatomical LEFT at waist-to-chest height. The torso turns with the strike; right arm is guided by whole-body rotation, not an isolated shoulder swing. Left shield arm stays near the ribs and counterbalances without obstructing the sword path. Rear heel pivots naturally. Show a clear horizontal cut, not an overhead or thrust. Decelerate with bent knees and return to the starting guard by four seconds; hold last second. One attack only.''',
 'heavy': '''Perform exactly ONE powerful OVERHEAD sword chop and recover. First 0.8 seconds balanced guard. Sink into both legs then raise the RIGHT sword hand high above the helmet, elbow bent and blade clearly pointing upward/back. Keep the LEFT hand on its shield; this is a strong single-handed chop with full-body drive. Pause briefly at the high loaded position to show anticipation. Push off the rear leg and take one short forward left step, driving hips and chest forward/down as the sword cuts vertically from ABOVE THE HEAD toward the floor in front. Torso folds forward with the force and both knees compress to absorb the finish. The blade decelerates just above the floor without scraping. Regain balance and recover guard by four seconds; hold last second. A clearly vertical heavy chop, not the horizontal light cut. Exactly one attack, no spin, no flourishing.''',
 'hit': '''Perform exactly ONE believable full-body stagger after a sudden unseen frontal impact, then recover. Begin in balanced guard for one second. The chest recoils sharply, shoulders and head react a fraction later, knees bend and pelvis shifts backward over the rear boot. Take one short backward recovery step to catch balance, with the leading boot briefly unweighted. Right sword hand and left shield arm follow momentum while retaining their grips; do not flail or drop equipment. Compress legs to absorb the recoil, regain forward intent and return to guard by four seconds. Finish alive and standing. No visible attacker, blood or effects. This must move pelvis and legs as well as upper body; not an isolated flinch or rigid torso tilt.''',
 'roll': '''Perform exactly ONE real forward diagonal SHOULDER ROLL and rise into guard. Begin guard for 0.7 seconds. Bend hips and knees deeply, push from both boots and tuck chin toward chest. Roll diagonally over the LEFT shoulder and upper back, rounding the spine and drawing BOTH knees tightly toward the chest; pelvis passes over shoulders, boots leave the ground, body visibly curls into a compact rolling shape. The shield stays close against left forearm/chest; the right hand carries the sword safely outside the roll with blade pointing away from body, never passing through the floor or torso. Continue the natural ground roll forward across about one body length, uncoil, plant the forward boot, then rear boot, and stand into low combat guard by four seconds. Final second holds guard. This is an actual articulated shoulder somersault, not a backward hop, cartwheel, stiff straight-body flip or teleport. Keep the whole action visible from fixed side three-quarter view and retain realistic floor contact.'''
}

REVISIONS={
 'heavy-v2': '''A real athletic swordfighter performs ONE powerful OVERHEAD sword chop. Fixed wide FRONT-RIGHT three-quarter camera clearly sees right shoulder, elbow, wrist and entire blade. Start half a second in low guard, sword in RIGHT hand near right hip. Visibly LIFT the right hand and sword high above the head, bending right elbow; blade points upward behind the crown. Brief high windup, then short left-foot forward step and rear-leg push drive a strong VERTICAL downward chop in front. Hips and chest fold forward with the blow, both knees compress; stop sword just above floor. Recover to starting guard and hold. Left hand carries a SMALL buckler LOW outside left ribs, never covering right arm. One-handed overhead chop, not horizontal slash or thrust. Fitted charcoal athletic shirt/trousers and flat boots, no armor or cape. Realistic natural speed, five seconds, plain gray studio, full body and blade always in view with ample margins, bright contact shadows. Stationary camera, no cuts.''',
 'light-v3': '''FRONT VIEW, fixed wide camera. A real athletic swordfighter performs ONE FOREHAND sword cut from his own RIGHT shoulder down across his body to the OPPOSITE LEFT hip. The right hand holds the sword. In this front view the sword starts on SCREEN LEFT beside the right shoulder, then sweeps forcefully across the chest to SCREEN RIGHT at left-hip height. Finish with RIGHT forearm crossing the front of the stomach and sword tip beyond the LEFT hip on screen right. This is a right-to-left FOREHAND, never a left-to-right backhand. Left hand holds a SMALL shield LOW beside the left ribs so both shoulders, elbows and hands stay visible. Load rear leg, twist torso toward right shoulder, then short left-foot forward step and strong hip/torso rotation drive the cut; knees compress in follow-through. Return to guard. One strike, five seconds, natural speed. Plain fitted dark athletic clothing, no armor/cape. Gray studio, full body and sword always visible, bright lighting, stationary camera, no cuts.''',
 'light-v2': '''A skilled adult swordfighter performs ONE forceful horizontal sword slash from their own RIGHT to their own LEFT, using whole-body rotation. Fixed three-quarter FRONT-RIGHT camera sees the sword arm clearly for the entire action; shield is on the far side, never hides right shoulder/elbow/wrist. Start with bent knees, left boot forward, right hand holding a short straight training sword near right waist, small round shield strapped to left forearm. After half a second wind the RIGHT hand/elbow back to the RIGHT side, load rear leg and twist hips/chest away. Then drive the rear boot, take a short left-foot forward step, rotate hips and chest back through front, and swing the RIGHT arm and sword horizontally across the FRONT of the torso from RIGHT side to LEFT side. The right shoulder, elbow and fist trace a clear large continuous horizontal arc; sword stays aligned naturally with the fist. Left shield remains tucked by left ribs below the sword path. Rear heel pivots, knees absorb finish, then return to guard. One slash only, clearly horizontal, not overhead/thrust. Fitted charcoal training shirt and trousers, flat boots, no armor/pauldrons/cape. Plain gray studio, bright readable lighting/contact shadows. Whole body and entire sword in frame with large margins, no camera movement/cuts/slow motion. Five-second motion-reference take.''',
 'hit-v3': '''A realistic adult stunt performer is suddenly knocked BACKWARD by an imaginary impact to the chest, visibly loses balance, then catches themselves. Side view, performer faces SCREEN RIGHT. Start in an alert slightly crouched stance with feet apart. After half a second, sternum and shoulders jerk BACKWARD toward SCREEN LEFT, head recoils, knees bend deeply and hips drop. The back/right foot urgently steps BACKWARD toward screen left to catch the falling body, front/left foot follows, then torso pitches forward to regain balance. Finish crouched but standing. One unmistakable heavy hit reaction, not walking forward, lunging, punching, blocking, attacking or dancing. No weapons, no shield, no other person, no impact effects; hands loosely bent near ribs and react with body inertia. Fitted charcoal athletic shirt and trousers, flat boots, visible knees and feet. Fixed wide side camera, whole body always visible with large margins, plain gray floor/background, clear contact shadows. Natural speed, no cuts, no camera motion. Five seconds total, one strong recoil and recovery.''',
 'guard-v2': '''A real athletic adult sword-and-shield fighter holds a LOW, alert combat guard and breathes naturally for five seconds. Full body visible from a FIXED SIDE three-quarter camera. LEFT foot one short step ahead, both knees visibly flexed, hips lowered, torso inclined slightly forward over the front thigh, weight centered over feet. RIGHT hand holds a short training sword with a closed fist near the right waist, sword points diagonally FORWARD and UP; right elbow bent and clear of ribs. LEFT forearm bears a small round training shield in front of left ribs, elbow bent. Maintain this exact guard through one slow breathing cycle and subtle whole-body weight shift, boots planted. No attacks, no steps, no upright posing. Plain fitted charcoal shirt and trousers, flat ankle boots, no armor, cloak or loose clothing so all joints are visible. Neutral gray floor/background, clear lighting and contact shadows. One uninterrupted realistic motion-capture reference, no camera movement or cuts. Entire body and props visible, performer only60 percent frame height.''',
 'hit-v2': '''A real athletic adult stunt performer in a sword-and-small-shield fighting guard performs ONE obvious full-body stagger from an imagined frontal blow. At1 second chest recoils, knees buckle and hips sink backward; promptly take one BIG recovery step backward with the rear/right boot, then the front/left boot follows to catch balance. Torso pitches back briefly then forward as legs absorb the impact. RIGHT sword arm and LEFT shield arm react naturally while retaining grips. By4 seconds recover the crouched fighting guard. This is an unmistakable stagger with moving hips and legs, not a subtle idle twitch. No attacker or effects. Short blunt training sword, small round forearm shield. Fitted charcoal shirt/trousers and flat boots, no armor/cape so knees are visible. Fixed SIDE three-quarter camera, wide full-body view including both feet at all times, plain neutral gray studio, clear light and contact shadows. Natural speed, one take, no camera motion.''',
 'roll-v2': '''A skilled adult stunt performer performs exactly ONE smooth FORWARD SHOULDER ROLL. Clear side profile facing SCREEN RIGHT. Start low combat crouch; push forcefully from rear foot, tuck chin and dive gently FORWARD over LEFT shoulder. Hips go UP and OVER the shoulders, both knees fold tightly to chest while the rounded upper back rolls on the mat. Momentum carries the compact curled body FORWARD toward screen right by one full body length. Uncurl, plant both feet, rise into low fighting guard. A proper martial-arts forward diagonal shoulder somersault, not sitting back or rocking backwards. Hold a SHORT foam training stick in RIGHT fist close outside right hip; a small foam forearm buckler remains tight on LEFT arm. These tiny props never obstruct the roll. Plain fitted charcoal athletic clothing and flat shoes, no armor/cape/long blade. Entire5-second motion in one fixed WIDE SIDE camera with ample floor space rightward, full body always visible. Neutral studio with mat floor, bright even lighting, realistic anatomy and motion, no cuts or camera movement.'''
}
name = sys.argv[1]
prompt = REVISIONS[name] if name in REVISIONS else BASE + MOTIONS[name]
DOC.mkdir(parents=True, exist_ok=True)
job = DOC / f'{name}-video-job.jsonl'
if job.exists() and job.stat().st_size:
    raise SystemExit(f'Job already recorded: {job}; attach to its ID, do not requeue.')
(DOC / f'{name}-video-prompt.txt').write_text(prompt)
cmd = ['npx','genex','video',prompt]
if name not in REVISIONS:cmd += ['--ref',str(REF)]
cmd += ['--duration','5','--resolution','768p','--out-dir','assets/player-combat-revision/source-videos','--no-wait','--json']
result = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)
job.write_text(result.stdout)
(DOC / f'{name}-video-stderr.log').write_text(result.stderr)
print(result.stdout)
if result.stderr: print(result.stderr, file=sys.stderr)
raise SystemExit(result.returncode)
